feature_name: OpenID
feature_description: |
  The properties for the oidc module
properties:
    - key: com.openexchange.oidc.enabled
      description: |
        Switch to enable disable the core OpenID feature.
      defaultValue: false
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.startDefaultBackend
      description: |
         Start the default core OpenID backend.
      defaultValue: false
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.clientId
      description: |
        The client id, which was assigned by thr OP to this client/backend
        on registration
      defaultValue:
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.rpRedirectURIAuth
      description: |
        The path to the authentication servlet of this backend
      defaultValue:
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.opAuthorizationEndpoint
      description: |
        The OPs authorization endpoint
      defaultValue:
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.opTokenEndpoint
      description: |
        The OPs token endpoint
      defaultValue:
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.clientSecret
      description: |
        The client secret, which was assigned by the OP to this client/backend
        on registration
      defaultValue:
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.opJwkSetEndpoint
      description: |
        The OPs JWK Set endpoint
      defaultValue:
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.jwsAlgorithm
      description: |
        The used JWS encryption algorithm
      defaultValue:
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.scope
      description: |
        The scope to request during OIDC authorization flow. This is a space-separated list of scope values, e.g. `openid offline`.
        Scope values are case-sensitive!
      defaultValue: openid
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.opIssuer
      description: |
        The OPs issuer path
      defaultValue:
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.responseType
      description: |
        The OPs response type, which also identifies the used flow
      defaultValue: code
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
  
    - key: com.openexchange.oidc.contextLookupClaim
      description: |
        Name of the ID token claim that will be used by the default backend to resolve a context.
      defaultValue: sub
      version: 7.10.3
      reloadable: true
      configcascadeAware: false
      related:
        - com.openexchange.oidc.contextLookupNamePart
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]

    - key: com.openexchange.oidc.contextLookupNamePart
      description: |
        Gets the name part of the ID token claim value used for
        determining the context of a user. Possible values are
        
        full - The full string as returned by the authorization server
        local-part - The local part of an email address (local-part@domain),
                     if the provided name matches such. In case the name does not match
                     an email address, the full string is taken.
        domain - The domain part of an email address (local-part@domain),
                 if the provided name matches such. In case the name does not match
                 an email address, "defaultcontext" is taken.
      defaultValue: domain
      version: 7.10.3
      reloadable: true
      configcascadeAware: false
      related:
        - com.openexchange.oidc.contextLookupClaim
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]

    - key: com.openexchange.oidc.userLookupClaim
      description: |
        Name of the ID token claim that will be used by the default backend to resolve a user.
      defaultValue: sub
      version: 7.10.3
      reloadable: true
      configcascadeAware: false
      related:
        - com.openexchange.oidc.userLookupNamePart
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]

    - key: com.openexchange.oidc.userLookupNamePart
      description: |
        Gets the name part of the ID token claim value used for
        determining a user within a context. Possible values are
        
        full - The full string as returned by the authorization server
        local-part - The local part of an email address (local-part@domain),
                     if the provided name matches such. In case the name does not match
                     an email address, the full string is taken.
        domain - The domain part of an email address (local-part@domain),
                 if the provided name matches such. In case the name does not match
                 an email address, the full string is taken.
      defaultValue: local-part
      version: 7.10.3
      reloadable: true
      configcascadeAware: false
      related:
        - com.openexchange.oidc.userLookupClaim
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.opLogoutEndpoint
      description: |
        The OPs logout endpoint
      defaultValue:
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.rpRedirectURIPostSSOLogout
      description: |
        The location where the Browser should be redirected after logout
        from OP
      defaultValue:
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.ssoLogout
      description: |
        Whether to redirect to the OP on logout trigger from client or not
      defaultValue: false
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.rpRedirectURILogout
      description: |
        Where to redirect the user after a valid logout
      defaultValue: false
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.autologinCookieMode
      description: |
        Which login mode is enabled look at {@link OIDCBackendConfig.AutologinMode} for all valid values,
        so far the following values are valid: {off, ox_direct, sso_redirect}.
        off - no autologin
        ox_direct - load user session from cookie and load Appsuite directly
        sso_redirect - check for a valid session on OPs side before login into
          a valid session loaded from a cookie
      defaultValue: 'off'
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.oauthRefreshTime
      description: |
        Time in milliseconds determining how long before the expiration of an
        OAuth access token a new access token should be requested, usually by
        exchanging a refresh token. In case refresh tokens are not issued,
        this value should be 0 to align max. allowed session use time to
        access token expiry.
      defaultValue: 60000
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related:
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.uiWebPath
      description: |
        This backends UI path
      defaultValue:
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]
      
    - key: com.openexchange.oidc.backendPath
      description: |
        This backends servlet path, which is appended to the default /oidc/ path.
      defaultValue:
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]

    - key: com.openexchange.oidc.hosts
      description: |
        This contains a comma separated list of hosts, that this backend supports.
      defaultValue:
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]

    - key: com.openexchange.oidc.failureRedirect
      description: |
        Set the redirect location for a failed authentication attempt because of an internal server error or a timeout
        since starting the login flow.
      defaultValue:
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]

    - key: com.openexchange.oidc.enablePasswordGrant
      description: |
        Enable API logins with username/password by using the Resource Owner
        Password Credentials Grant (https://tools.ietf.org/html/rfc6749#section-4.3) to authenticate.
      defaultValue: false
      version: 7.10.3
      reloadable: false
      configcascadeAware: false
      related:
        - com.openexchange.oidc.passwordGrantUserNamePart
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]

    - key: com.openexchange.oidc.passwordGrantUserNamePart
      description: |
        Gets the name part to be used for an issued Resource Owner Password
        Credentials Grant (https://tools.ietf.org/html/rfc6749#section-4.3)
        request. The part is taken from the user-provided login name.
        
        full - The full string as provided by the user/client
        local-part - The local part of an email address (local-part@domain),
                     if the provided name matches such. In case the name does not match
                     an email address, the full string is taken.
        domain - The domain part of an email address (local-part@domain),
                 if the provided name matches such. In case the name does not match
                 an email address, the full string is taken.
      defaultValue: full
      version: 7.10.3
      reloadable: true
      configcascadeAware: false
      related:
        - com.openexchange.oidc.enablePasswordGrant
      file: openid.properties 
      packageName: open-xchange-oidc
      tags: ["OpenID"]

    - key: com.openexchange.oidc.tokenLockTimeoutSeconds
      description: |
        Lock timeout before giving up trying to refresh an access token for
        a session. If multiple threads try to check or refresh the access token
        at the same time, only one gets a lock and blocks the others. In case
        of a timeout, this is logged as a temporary issue and the request continued
        as usual.
      defaultValue: 5
      version: 7.10.3
      reloadable: true
      configcascadeAware: false
      file: openid.properties
      packageName: open-xchange-oidc
      tags: ["OpenID"]

    - key: com.openexchange.oidc.tryRecoverStoredTokens
      description: |
        Whether token refresh should try to recover valid tokens from
        the session instance that is present in distributed session storage.
        This is only tried as a fall-back, after token refresh failed with an
        `invalid_grant` error.
        
        Usually this should not be needed, it might help to circumvent user impact
        if for any reason user sessions are alive on more than one server concurrently.
        Due to sticky sessions this should never be the case.
      defaultValue: false
      version: 7.10.3
      reloadable: true
      configcascadeAware: false
      file: openid.properties
      packageName: open-xchange-oidc
      tags: ["OpenID"]

    - key: com.openexchange.httpclient.oidc.totalConnections
      description: |
        The max. number of concurrent HTTP connections that may be established. If you have specified more
        than one hosts, this setting should be configured so that  
        connectionsPerRoute < totalConnections <= n * connectionsPerRoute.
      defaultValue: 100
      version: 7.10.4
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties
      packageName: open-xchange-oidc
      tags: ["OpenID", "Limit"]
      
    - key: com.openexchange.httpclient.oidc.connectionsPerRoute
      description: |
        The max. number of concurrent HTTP connections that may be established with a certain endpoint.
      defaultValue: 100
      version: 7.10.4
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties
      packageName: open-xchange-oidc
      tags: ["OpenID", "Limit"]
      
    - key: com.openexchange.httpclient.oidc.connectTimeout
      description: |
        The connection timeout in milliseconds. If establishing a new HTTP connection to a certain
        host exceeds this value, a timeout exception is thrown.
      defaultValue: 5000
      version: 7.10.4
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties
      packageName: open-xchange-oidc
      tags: ["OpenID", "Timeout"]
      
    - key: com.openexchange.httpclient.oidc.readTimeout
      description: |
        The socket read timeout in milliseconds. If waiting for the next expected TCP packet exceeds
        this value, a timeout exception is thrown.
      defaultValue: 15000
      version: 7.10.4
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties
      packageName: open-xchange-oidc
      tags: ["OpenID", "Timeout"]

    - key: com.openexchange.httpclient.oidc.connectionRequestTimeout
      description: |
        The pool timeout in milliseconds. If waiting for the next available HTTP connection from pool exceeds
        this value, a timeout exception is thrown.
      defaultValue: 15000
      version: 7.10.4
      reloadable: true
      configcascadeAware: false
      related: 
      file: openid.properties
      packageName: open-xchange-oidc
      tags: ["OpenID", "Timeout"]
