feature_name: Subscribe
properties:
    - key: com.openexchange.subscribe.autorun
      description: |
        Defines whether subscriptions should be run automatically on login, if a given interval has elapsed.
        The intervals default to one day, but can be configured individually by subscription type
        in the subscription source specific configuration files.
      defaultValue: false
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: subscribe.properties
      packageName: open-xchange-core
      tags: ["Subscribe"]
    - key: com.openexchange.subscribe.mslive.contact.autorunInterval
      description: |
        Defines the subscription refresh autorun interval for MS Live.
      defaultValue: 1d
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: mslivesubscribe.properties
      packageName: open-xchange-subscribe
      tags: ["MS Live Connect", "Contact", "Subscribe"]
    - key: com.openexchange.subscribe.socialplugin.yahoo
      description: |
        Enable/disable Yahoo subscribe service.
      defaultValue: true
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: yahoosubscribe.properties
      packageName: open-xchange-subscribe
      tags: ["Yahoo", "Contact", "Subscribe"]
    - key: com.openexchange.subscribe.socialplugin.yahoo.autorunInterval
      description: |
        Defines the subscription refresh autorun interval for Yahoo.
      defaultValue: 1d
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: yahoosubscribe.properties
      packageName: open-xchange-subscribe
      tags: ["Yahoo", "Contact", "Subscribe"]
    - key: com.openexchange.subscribe.socialplugin.xing
      description: |
        Enable/disable XING subscribe service.
      defaultValue: true
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: xingsubscribe.properties
      packageName: open-xchange-subscribe
      tags: ["Xing", "Contact", "Subscribe"]
    - key: com.openexchange.subscribe.socialplugin.xing.autorunInterval
      description: |
        Defines the subscription refresh autorun interval for XING.
      defaultValue: 1d
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: xingsubscribe.properties
      packageName: open-xchange-subscribe
      tags: ["Xing", "Contact", "Subscribe"]